[phases.setup]
nixPkgs = ["...", "nodejs-18_x", "nginx"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "sh start.sh"

[staticAssets]
"dist" = "/"
