databases:
  - name: jivs-postgres
    databaseName: jivs
    user: jivs_user
    plan: free
    region: oregon

services:
  # Backend API
  - type: web
    name: jivs-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: jivs-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: jivs-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: jivs-postgres
          property: password
    healthCheckPath: /actuator/health

  # Frontend
  - type: web
    name: jivs-frontend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: jivs-backend
          property: host
