[phases.setup]
nixPkgs = ["...", "maven", "jdk21"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=production -jar target/jivs-platform-1.0.0.jar"
