spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    clean-disabled: false

logging:
  level:
    root: INFO
    com.jivs.platform: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jivs:
  security:
    jwt:
      secret: dev-secret-key-only-for-development-do-not-use-in-production
    cors:
      allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:5173,http://localhost:5174

  encryption:
    key: dev-encryption-key-only-for-development

  storage:
    provider: local
    local:
      base-path: /tmp/jivs/storage

  extraction:
    temp-directory: /tmp/jivs/extraction

  document:
    ocr-enabled: false
