spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672

logging:
  level:
    root: INFO
    com.jivs.platform: DEBUG

jivs:
  security:
    jwt:
      secret: test-secret-key-for-testing-only
      expiration: 3600000 # 1 hour

  storage:
    provider: local
    local:
      base-path: /tmp/jivs-test/storage

  extraction:
    max-parallel-jobs: 2
    batch-size: 100

  document:
    ocr-enabled: false
